using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace BackNoDiscord.Infrastructure;

public static class DatabaseSchemaInitializer
{
    public static async Task InitializeAsync(IServiceProvider services)
    {
        await using var scope = services.CreateAsyncScope();
        var dbContext = scope.ServiceProvider.GetRequiredService<AppDbContext>();

        await dbContext.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS refresh_tokens (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                token_hash text NOT NULL,
                created_at timestamptz NOT NULL,
                expires_at timestamptz NOT NULL,
                revoked_at timestamptz NULL,
                replaced_by_token_hash text NULL,
                user_agent text NOT NULL DEFAULT '',
                device_label text NOT NULL DEFAULT '',
                last_ip text NOT NULL DEFAULT '',
                last_used_at timestamptz NOT NULL DEFAULT NOW()
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ix_refresh_tokens_token_hash ON refresh_tokens (token_hash);
            CREATE INDEX IF NOT EXISTS ix_refresh_tokens_user_id_expires_at ON refresh_tokens (user_id, expires_at);

            CREATE TABLE IF NOT EXISTS shared_server_snapshots (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                server_id character varying(160) NOT NULL,
                owner_user_id text NOT NULL,
                snapshot_json text NOT NULL,
                created_at timestamptz NOT NULL,
                updated_at timestamptz NOT NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ix_shared_server_snapshots_server_id ON shared_server_snapshots (server_id);
            CREATE INDEX IF NOT EXISTS ix_shared_server_snapshots_owner_user_id ON shared_server_snapshots (owner_user_id);

            CREATE TABLE IF NOT EXISTS server_invites (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code character varying(20) NOT NULL,
                owner_user_id text NOT NULL,
                created_at timestamptz NOT NULL,
                expires_at timestamptz NOT NULL,
                snapshot_json text NOT NULL,
                redeemed_user_ids_json text NOT NULL DEFAULT '[]'
            );
            ALTER TABLE IF EXISTS server_invites
                ALTER COLUMN code TYPE character varying(20);
            CREATE UNIQUE INDEX IF NOT EXISTS ix_server_invites_code ON server_invites (code);
            CREATE INDEX IF NOT EXISTS ix_server_invites_owner_user_id_expires_at ON server_invites (owner_user_id, expires_at);

            CREATE TABLE IF NOT EXISTS friendships (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_low_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                user_high_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                created_at timestamptz NOT NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ix_friendships_user_low_id_user_high_id ON friendships (user_low_id, user_high_id);
            CREATE INDEX IF NOT EXISTS ix_friendships_created_at ON friendships (created_at);

            CREATE TABLE IF NOT EXISTS friend_requests (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sender_user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                receiver_user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                user_low_id integer NOT NULL,
                user_high_id integer NOT NULL,
                status character varying(16) NOT NULL,
                created_at timestamptz NOT NULL,
                responded_at timestamptz NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ix_friend_requests_pending_pair
                ON friend_requests (user_low_id, user_high_id)
                WHERE status = 'pending';
            CREATE INDEX IF NOT EXISTS ix_friend_requests_receiver_status_created_at
                ON friend_requests (receiver_user_id, status, created_at);
            CREATE INDEX IF NOT EXISTS ix_friend_requests_sender_status_created_at
                ON friend_requests (sender_user_id, status, created_at);

            CREATE TABLE IF NOT EXISTS user_blocks (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                blocker_user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                blocked_user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                created_at timestamptz NOT NULL DEFAULT NOW()
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ix_user_blocks_blocker_blocked
                ON user_blocks (blocker_user_id, blocked_user_id);
            CREATE INDEX IF NOT EXISTS ix_user_blocks_blocker_user_id
                ON user_blocks (blocker_user_id);
            CREATE INDEX IF NOT EXISTS ix_user_blocks_blocked_user_id
                ON user_blocks (blocked_user_id);

            CREATE TABLE IF NOT EXISTS group_conversations (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                owner_user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                title character varying(120) NOT NULL,
                created_at timestamptz NOT NULL,
                updated_at timestamptz NOT NULL,
                active_call_channel character varying(160) NULL,
                active_call_started_at timestamptz NULL
            );
            CREATE INDEX IF NOT EXISTS ix_group_conversations_owner_user_id
                ON group_conversations (owner_user_id);
            CREATE INDEX IF NOT EXISTS ix_group_conversations_updated_at
                ON group_conversations (updated_at);
            ALTER TABLE group_conversations
                ADD COLUMN IF NOT EXISTS avatar_url text NULL;

            CREATE TABLE IF NOT EXISTS group_conversation_members (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                conversation_id integer NOT NULL REFERENCES group_conversations(id) ON DELETE CASCADE,
                user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                role character varying(16) NOT NULL DEFAULT 'member',
                joined_at timestamptz NOT NULL,
                added_by_user_id integer NULL REFERENCES users(id) ON DELETE SET NULL,
                muted_until timestamptz NULL,
                is_banned boolean NOT NULL DEFAULT false,
                banned_at timestamptz NULL,
                banned_by_user_id integer NULL REFERENCES users(id) ON DELETE SET NULL
            );
            ALTER TABLE group_conversation_members
                ADD COLUMN IF NOT EXISTS last_read_at timestamptz NULL;
            CREATE UNIQUE INDEX IF NOT EXISTS ix_group_conversation_members_conversation_user
                ON group_conversation_members (conversation_id, user_id);
            CREATE INDEX IF NOT EXISTS ix_group_conversation_members_user_banned
                ON group_conversation_members (user_id, is_banned);
            CREATE INDEX IF NOT EXISTS ix_group_conversation_members_conversation_banned
                ON group_conversation_members (conversation_id, is_banned);

            CREATE TABLE IF NOT EXISTS phone_verification_codes (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                phone_number character varying(16) NOT NULL,
                verification_token_hash text NOT NULL,
                code_hash text NOT NULL,
                created_at timestamptz NOT NULL,
                expires_at timestamptz NOT NULL,
                last_sent_at timestamptz NOT NULL,
                attempt_count integer NOT NULL DEFAULT 0,
                verified_at timestamptz NULL,
                consumed_at timestamptz NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ix_phone_verification_codes_verification_token_hash ON phone_verification_codes (verification_token_hash);
            CREATE INDEX IF NOT EXISTS ix_phone_verification_codes_phone_number_created_at ON phone_verification_codes (phone_number, created_at);

            CREATE TABLE IF NOT EXISTS email_verification_codes (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                email text NOT NULL,
                verification_token_hash text NOT NULL,
                code_hash text NOT NULL,
                created_at timestamptz NOT NULL,
                expires_at timestamptz NOT NULL,
                last_sent_at timestamptz NOT NULL,
                attempt_count integer NOT NULL DEFAULT 0,
                verified_at timestamptz NULL,
                consumed_at timestamptz NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ix_email_verification_codes_verification_token_hash ON email_verification_codes (verification_token_hash);
            CREATE INDEX IF NOT EXISTS ix_email_verification_codes_user_id ON email_verification_codes (user_id);
            CREATE INDEX IF NOT EXISTS ix_email_verification_codes_email ON email_verification_codes (email);

            CREATE TABLE IF NOT EXISTS qr_login_sessions (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                session_id character varying(64) NOT NULL,
                browser_token_hash text NOT NULL,
                scanner_token_hash text NOT NULL,
                created_at timestamptz NOT NULL,
                expires_at timestamptz NOT NULL,
                approved_at timestamptz NULL,
                approved_user_id integer NULL REFERENCES users(id) ON DELETE SET NULL,
                consumed_at timestamptz NULL,
                canceled_at timestamptz NULL,
                requested_ip text NOT NULL DEFAULT '',
                requested_user_agent text NOT NULL DEFAULT '',
                approved_ip text NULL,
                approved_user_agent text NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ix_qr_login_sessions_session_id ON qr_login_sessions (session_id);
            CREATE UNIQUE INDEX IF NOT EXISTS ix_qr_login_sessions_browser_token_hash ON qr_login_sessions (browser_token_hash);
            CREATE INDEX IF NOT EXISTS ix_qr_login_sessions_expires_consumed ON qr_login_sessions (expires_at, consumed_at);

            CREATE TABLE IF NOT EXISTS message_reactions (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                message_id integer NOT NULL REFERENCES chatmessages(id) ON DELETE CASCADE,
                channel_id character varying(160) NOT NULL,
                reactor_user_id text NOT NULL,
                reaction_key character varying(32) NOT NULL,
                reaction_glyph character varying(16) NOT NULL,
                created_at timestamptz NOT NULL
            );
            CREATE TABLE IF NOT EXISTS push_subscriptions (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                endpoint text NOT NULL,
                p256dh_key text NOT NULL,
                auth_key text NOT NULL,
                user_agent text NOT NULL DEFAULT '',
                device_label text NOT NULL DEFAULT '',
                created_at timestamptz NOT NULL,
                updated_at timestamptz NOT NULL,
                last_success_at timestamptz NULL,
                last_failure_at timestamptz NULL,
                last_failure_reason text NULL,
                is_active boolean NOT NULL DEFAULT true
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ix_message_reactions_message_user_key
                ON message_reactions (message_id, reactor_user_id, reaction_key);
            CREATE INDEX IF NOT EXISTS ix_message_reactions_message_key
                ON message_reactions (message_id, reaction_key);
            CREATE INDEX IF NOT EXISTS ix_message_reactions_channel_created_at
                ON message_reactions (channel_id, created_at);
            CREATE UNIQUE INDEX IF NOT EXISTS ix_push_subscriptions_endpoint
                ON push_subscriptions (endpoint);
            CREATE INDEX IF NOT EXISTS ix_push_subscriptions_user_active_updated
                ON push_subscriptions (user_id, is_active, updated_at);

            CREATE TABLE IF NOT EXISTS user_integrations (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                provider character varying(32) NOT NULL,
                display_name character varying(120) NOT NULL DEFAULT '',
                external_user_id text NOT NULL DEFAULT '',
                display_in_profile boolean NOT NULL DEFAULT true,
                use_as_status boolean NOT NULL DEFAULT true,
                activity_kind character varying(32) NOT NULL DEFAULT '',
                activity_title character varying(160) NOT NULL DEFAULT '',
                activity_subtitle character varying(160) NOT NULL DEFAULT '',
                activity_details text NOT NULL DEFAULT '',
                activity_updated_at timestamptz NULL,
                access_token_encrypted text NOT NULL DEFAULT '',
                refresh_token_encrypted text NOT NULL DEFAULT '',
                token_expires_at timestamptz NULL,
                connected_at timestamptz NOT NULL DEFAULT NOW(),
                updated_at timestamptz NOT NULL DEFAULT NOW()
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ix_user_integrations_user_provider
                ON user_integrations (user_id, provider);
            CREATE INDEX IF NOT EXISTS ix_user_integrations_user_status_activity
                ON user_integrations (user_id, use_as_status, activity_updated_at);
            ALTER TABLE IF EXISTS chatmessages
                ADD COLUMN IF NOT EXISTS message_encrypted text NULL;
            ALTER TABLE IF EXISTS chatmessages
                ADD COLUMN IF NOT EXISTS read_at timestamp NULL;
            ALTER TABLE IF EXISTS chatmessages
                ADD COLUMN IF NOT EXISTS read_by_user_id text NULL;
            ALTER TABLE IF EXISTS chatmessages
                ADD COLUMN IF NOT EXISTS is_deleted boolean NOT NULL DEFAULT false;
            ALTER TABLE IF EXISTS users
                ADD COLUMN IF NOT EXISTS is_email_verified boolean NOT NULL DEFAULT true;
            ALTER TABLE IF EXISTS users
                ADD COLUMN IF NOT EXISTS phone_number character varying(16) NULL;
            ALTER TABLE IF EXISTS users
                ADD COLUMN IF NOT EXISTS is_phone_verified boolean NOT NULL DEFAULT false;
            ALTER TABLE IF EXISTS users
                ADD COLUMN IF NOT EXISTS totp_secret text NULL;
            ALTER TABLE IF EXISTS users
                ADD COLUMN IF NOT EXISTS is_totp_enabled boolean NOT NULL DEFAULT false;
            ALTER TABLE IF EXISTS users
                ADD COLUMN IF NOT EXISTS totp_enabled_at timestamptz NULL;
            ALTER TABLE IF EXISTS users
                ADD COLUMN IF NOT EXISTS avatar_url text NULL;
            ALTER TABLE IF EXISTS users
                ADD COLUMN IF NOT EXISTS avatar_frame_json text NULL;
            ALTER TABLE IF EXISTS users
                ADD COLUMN IF NOT EXISTS profile_background_url text NULL;
            ALTER TABLE IF EXISTS users
                ADD COLUMN IF NOT EXISTS profile_background_frame_json text NULL;
            ALTER TABLE IF EXISTS users
                ADD COLUMN IF NOT EXISTS last_seen_at timestamptz NULL;
            ALTER TABLE IF EXISTS users
                ADD COLUMN IF NOT EXISTS nickname character varying(50) NULL;
            ALTER TABLE IF EXISTS refresh_tokens
                ADD COLUMN IF NOT EXISTS user_agent text NOT NULL DEFAULT '';
            ALTER TABLE IF EXISTS refresh_tokens
                ADD COLUMN IF NOT EXISTS device_label text NOT NULL DEFAULT '';
            ALTER TABLE IF EXISTS refresh_tokens
                ADD COLUMN IF NOT EXISTS last_ip text NOT NULL DEFAULT '';
            ALTER TABLE IF EXISTS refresh_tokens
                ADD COLUMN IF NOT EXISTS last_used_at timestamptz NOT NULL DEFAULT NOW();
            ALTER TABLE IF EXISTS push_subscriptions
                ADD COLUMN IF NOT EXISTS user_agent text NOT NULL DEFAULT '';
            ALTER TABLE IF EXISTS push_subscriptions
                ADD COLUMN IF NOT EXISTS device_label text NOT NULL DEFAULT '';
            ALTER TABLE IF EXISTS push_subscriptions
                ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT NOW();
            ALTER TABLE IF EXISTS push_subscriptions
                ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT NOW();
            ALTER TABLE IF EXISTS push_subscriptions
                ADD COLUMN IF NOT EXISTS last_success_at timestamptz NULL;
            ALTER TABLE IF EXISTS push_subscriptions
                ADD COLUMN IF NOT EXISTS last_failure_at timestamptz NULL;
            ALTER TABLE IF EXISTS push_subscriptions
                ADD COLUMN IF NOT EXISTS last_failure_reason text NULL;
            ALTER TABLE IF EXISTS push_subscriptions
                ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;
            ALTER TABLE IF EXISTS user_integrations
                ADD COLUMN IF NOT EXISTS display_name character varying(120) NOT NULL DEFAULT '';
            ALTER TABLE IF EXISTS user_integrations
                ADD COLUMN IF NOT EXISTS external_user_id text NOT NULL DEFAULT '';
            ALTER TABLE IF EXISTS user_integrations
                ADD COLUMN IF NOT EXISTS display_in_profile boolean NOT NULL DEFAULT true;
            ALTER TABLE IF EXISTS user_integrations
                ADD COLUMN IF NOT EXISTS use_as_status boolean NOT NULL DEFAULT true;
            ALTER TABLE IF EXISTS user_integrations
                ADD COLUMN IF NOT EXISTS activity_kind character varying(32) NOT NULL DEFAULT '';
            ALTER TABLE IF EXISTS user_integrations
                ADD COLUMN IF NOT EXISTS activity_title character varying(160) NOT NULL DEFAULT '';
            ALTER TABLE IF EXISTS user_integrations
                ADD COLUMN IF NOT EXISTS activity_subtitle character varying(160) NOT NULL DEFAULT '';
            ALTER TABLE IF EXISTS user_integrations
                ADD COLUMN IF NOT EXISTS activity_details text NOT NULL DEFAULT '';
            ALTER TABLE IF EXISTS user_integrations
                ADD COLUMN IF NOT EXISTS activity_updated_at timestamptz NULL;
            ALTER TABLE IF EXISTS user_integrations
                ADD COLUMN IF NOT EXISTS access_token_encrypted text NOT NULL DEFAULT '';
            ALTER TABLE IF EXISTS user_integrations
                ADD COLUMN IF NOT EXISTS refresh_token_encrypted text NOT NULL DEFAULT '';
            ALTER TABLE IF EXISTS user_integrations
                ADD COLUMN IF NOT EXISTS token_expires_at timestamptz NULL;
            ALTER TABLE IF EXISTS user_integrations
                ADD COLUMN IF NOT EXISTS connected_at timestamptz NOT NULL DEFAULT NOW();
            ALTER TABLE IF EXISTS user_integrations
                ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT NOW();
            ALTER TABLE IF EXISTS users
                ALTER COLUMN email DROP NOT NULL;
            ALTER TABLE IF EXISTS chatmessages
                ALTER COLUMN message DROP NOT NULL;
            ALTER TABLE IF EXISTS chatmessages
                ALTER COLUMN photourl DROP NOT NULL;

            CREATE INDEX IF NOT EXISTS ix_chatmessages_channelid_timestamp ON chatmessages (channelid, timestamp);
            CREATE INDEX IF NOT EXISTS ix_chatmessages_channelid_id ON chatmessages (channelid, id);
            CREATE INDEX IF NOT EXISTS ix_chatmessages_timestamp ON chatmessages (timestamp);
            CREATE INDEX IF NOT EXISTS ix_chatmessages_channelid_read_at ON chatmessages (channelid, read_at);
            DROP INDEX IF EXISTS "IX_users_email";
            DROP INDEX IF EXISTS ix_users_email;
            CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email_not_null ON users (email) WHERE email IS NOT NULL;
            CREATE UNIQUE INDEX IF NOT EXISTS ix_users_phone_number ON users (phone_number) WHERE phone_number IS NOT NULL;
            UPDATE users SET is_email_verified = true WHERE is_email_verified IS NULL;
            UPDATE users SET email = NULL WHERE TRIM(COALESCE(email, '')) = '';
            UPDATE users
            SET nickname = TRIM(CONCAT(COALESCE(first_name, ''), ' ', COALESCE(last_name, '')))
            WHERE nickname IS NULL OR TRIM(COALESCE(nickname, '')) = '';
            UPDATE users
            SET nickname = COALESCE(NULLIF(TRIM(nickname), ''), COALESCE(email, 'User'))
            WHERE TRIM(COALESCE(nickname, '')) = '';
            ALTER TABLE IF EXISTS users
                ALTER COLUMN nickname SET NOT NULL;
            """);
    }
}
