using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace BackNoDiscord.Infrastructure;

public static class DatabaseSchemaInitializer
{
    public static async Task InitializeAsync(IServiceProvider services)
    {
        await using var scope = services.CreateAsyncScope();
        var dbContext = scope.ServiceProvider.GetRequiredService<AppDbContext>();

        await dbContext.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS refresh_tokens (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                token_hash text NOT NULL,
                created_at timestamptz NOT NULL,
                expires_at timestamptz NOT NULL,
                revoked_at timestamptz NULL,
                replaced_by_token_hash text NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ix_refresh_tokens_token_hash ON refresh_tokens (token_hash);
            CREATE INDEX IF NOT EXISTS ix_refresh_tokens_user_id_expires_at ON refresh_tokens (user_id, expires_at);

            CREATE TABLE IF NOT EXISTS shared_server_snapshots (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                server_id character varying(160) NOT NULL,
                owner_user_id text NOT NULL,
                snapshot_json text NOT NULL,
                created_at timestamptz NOT NULL,
                updated_at timestamptz NOT NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ix_shared_server_snapshots_server_id ON shared_server_snapshots (server_id);
            CREATE INDEX IF NOT EXISTS ix_shared_server_snapshots_owner_user_id ON shared_server_snapshots (owner_user_id);

            CREATE TABLE IF NOT EXISTS server_invites (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code character varying(16) NOT NULL,
                owner_user_id text NOT NULL,
                created_at timestamptz NOT NULL,
                expires_at timestamptz NOT NULL,
                snapshot_json text NOT NULL,
                redeemed_user_ids_json text NOT NULL DEFAULT '[]'
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ix_server_invites_code ON server_invites (code);
            CREATE INDEX IF NOT EXISTS ix_server_invites_owner_user_id_expires_at ON server_invites (owner_user_id, expires_at);

            CREATE TABLE IF NOT EXISTS friendships (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_low_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                user_high_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                created_at timestamptz NOT NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ix_friendships_user_low_id_user_high_id ON friendships (user_low_id, user_high_id);
            CREATE INDEX IF NOT EXISTS ix_friendships_created_at ON friendships (created_at);

            CREATE TABLE IF NOT EXISTS phone_verification_codes (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                phone_number character varying(16) NOT NULL,
                verification_token_hash text NOT NULL,
                code_hash text NOT NULL,
                created_at timestamptz NOT NULL,
                expires_at timestamptz NOT NULL,
                last_sent_at timestamptz NOT NULL,
                attempt_count integer NOT NULL DEFAULT 0,
                verified_at timestamptz NULL,
                consumed_at timestamptz NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ix_phone_verification_codes_verification_token_hash ON phone_verification_codes (verification_token_hash);
            CREATE INDEX IF NOT EXISTS ix_phone_verification_codes_phone_number_created_at ON phone_verification_codes (phone_number, created_at);

            CREATE TABLE IF NOT EXISTS email_verification_codes (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                email text NOT NULL,
                verification_token_hash text NOT NULL,
                code_hash text NOT NULL,
                created_at timestamptz NOT NULL,
                expires_at timestamptz NOT NULL,
                last_sent_at timestamptz NOT NULL,
                attempt_count integer NOT NULL DEFAULT 0,
                verified_at timestamptz NULL,
                consumed_at timestamptz NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ix_email_verification_codes_verification_token_hash ON email_verification_codes (verification_token_hash);
            CREATE INDEX IF NOT EXISTS ix_email_verification_codes_user_id ON email_verification_codes (user_id);
            CREATE INDEX IF NOT EXISTS ix_email_verification_codes_email ON email_verification_codes (email);

            CREATE TABLE IF NOT EXISTS message_reactions (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                message_id integer NOT NULL REFERENCES chatmessages(id) ON DELETE CASCADE,
                channel_id character varying(160) NOT NULL,
                reactor_user_id text NOT NULL,
                reaction_key character varying(32) NOT NULL,
                reaction_glyph character varying(16) NOT NULL,
                created_at timestamptz NOT NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ix_message_reactions_message_user_key
                ON message_reactions (message_id, reactor_user_id, reaction_key);
            CREATE INDEX IF NOT EXISTS ix_message_reactions_message_key
                ON message_reactions (message_id, reaction_key);
            CREATE INDEX IF NOT EXISTS ix_message_reactions_channel_created_at
                ON message_reactions (channel_id, created_at);

            ALTER TABLE IF EXISTS chatmessages
                ADD COLUMN IF NOT EXISTS message_encrypted text NULL;
            ALTER TABLE IF EXISTS chatmessages
                ADD COLUMN IF NOT EXISTS read_at timestamp NULL;
            ALTER TABLE IF EXISTS chatmessages
                ADD COLUMN IF NOT EXISTS read_by_user_id text NULL;
            ALTER TABLE IF EXISTS chatmessages
                ADD COLUMN IF NOT EXISTS is_deleted boolean NOT NULL DEFAULT false;
            ALTER TABLE IF EXISTS users
                ADD COLUMN IF NOT EXISTS is_email_verified boolean NOT NULL DEFAULT true;
            ALTER TABLE IF EXISTS users
                ADD COLUMN IF NOT EXISTS phone_number character varying(16) NULL;
            ALTER TABLE IF EXISTS users
                ADD COLUMN IF NOT EXISTS is_phone_verified boolean NOT NULL DEFAULT false;
            ALTER TABLE IF EXISTS users
                ADD COLUMN IF NOT EXISTS avatar_url text NULL;
            ALTER TABLE IF EXISTS users
                ALTER COLUMN email DROP NOT NULL;
            ALTER TABLE IF EXISTS chatmessages
                ALTER COLUMN message DROP NOT NULL;
            ALTER TABLE IF EXISTS chatmessages
                ALTER COLUMN photourl DROP NOT NULL;

            CREATE INDEX IF NOT EXISTS ix_chatmessages_channelid_timestamp ON chatmessages (channelid, timestamp);
            CREATE INDEX IF NOT EXISTS ix_chatmessages_timestamp ON chatmessages (timestamp);
            CREATE INDEX IF NOT EXISTS ix_chatmessages_channelid_read_at ON chatmessages (channelid, read_at);
            DROP INDEX IF EXISTS "IX_users_email";
            DROP INDEX IF EXISTS ix_users_email;
            CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email_not_null ON users (email) WHERE email IS NOT NULL;
            CREATE UNIQUE INDEX IF NOT EXISTS ix_users_phone_number ON users (phone_number) WHERE phone_number IS NOT NULL;
            UPDATE users SET is_email_verified = true WHERE is_email_verified IS NULL;
            UPDATE users SET email = NULL WHERE TRIM(COALESCE(email, '')) = '';
            """);
    }
}
